### ISSUE TITLE
Method for releasing a new gem version

### ISSUE THREAD

**Issue by brendon** [qoobaa/vcard#27]
Hi @qoobaa, thanks for the write access. I've cleaned up the tests to remove warnings etc... and everything looks good.

I was wondering if you could let me know the process for releasing a new gem version for this repo? No rush :)

**Comment by qoobaa** [comment]
I've just released a new gem version. I do it by bumping the version number and by running `rake release` task, but you need to have permissions granted if you want to push it to rubygems.org. I can grant you permissions if you plan to do some more changes in the future.

**Comment by brendon** [comment]
Thanks @qoobaa, given the tests are all green, I'm probably going to leave things as is for now. I'll be in touch in the future if the need arises :)
