### ISSUE TITLE
New release with ruby25 and ruby26 support

### ISSUE THREAD

**Issue by orlitzky** [qoobaa/vcard#30]
Hi, the current release of the vcard gem only supports up to ruby24. That ruby branch will only receive security updates for another 5 months according to https://www.ruby-lang.org/en/downloads/branches/ so it's important for us to upgrade by then. But to do that, we need a version of vcard that will work with a newer ruby. Please consider a new release tested against those versions.

**Comment by brendon** [comment]
Hi @orlitzky, would you mind putting together a PR for this? :)

**Comment by qoobaa** [comment]
I get your point. I can have a look, but not earlier than next month. Also, I haven't used vcard for a while - a PR would be great.

**Comment by orlitzky** [comment]
I will _eventually_ have to do something about this myself, but the way I use vcard is as a dependency of a plugin of redmine in Gentoo. What prompted me to open this issue was the announcement that the associated package will be removed from Gentoo: https://archives.gentoo.org/gentoo-dev-announce/message/f7ccfd69d395091db30bcc34b481724b

Since vcard is so deep down the chain of things I use, I have a hundred other more immediate problems =)

(and I don't actually know what's needed for ruby25/ruby26 compatibility)

**Comment by brendon** [comment]
I'd doubt there will be any code incompatibility but you never know :) A good start would be just to create a PR that changes the travis.yml to test against newer rubies and see what happens from there.

**Comment by orlitzky** [comment]
> I'd doubt there will be any code incompatibility but you never know :) A good start would be just to create a PR that changes the travis.yml to test against newer rubies and see what happens from there.

I haven't tested it myself, so no promises, but ruby24 support was enabled in Gentoo in https://github.com/gentoo/gentoo/commit/7d024f5943047a7ee60218679f8441c8242679c5 and it looks a lot like he tested it with ruby25 and found incompatibilities.

**Comment by SaaSFlowHoldings1** [comment]
Tests pass on 2.4, 2.5, 2.6 - I'm assuming everything runs smoothly. Please open another issue if something doesn't work correctly.

**Comment by qoobaa** [comment]
Tests pass on 2.4, 2.5, 2.6 - I'm assuming everything runs smoothly. Please open another issue if something doesn't work correctly.

**Comment by orlitzky** [comment]
Thanks! I bumped our version in Gentoo, further punting the problem to our users to report any issues =)
